Update Docs testing in Simulation
bit-bots/bitbots_tools pull request #150
Opened 2023-06-09 14:15 UTC by jaagut

## Proposed changes

## Related issues

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

2023-08-17 10:11 UTC, timonegk requested changes

2023-08-17 10:11 UTC, timonegk commented on bitbots_docs/docs/manual/testing/sim_test.rst
> +- Test the behavior independent from vision:
But the command tests the behavior with vision and everything

2023-08-30 11:31 UTC, Flova commented
Ping @jaagut

2023-09-08 13:16 UTC, timonegk requested changes

2023-09-08 13:16 UTC, timonegk commented on bitbots_docs/docs/manual/testing/sim_test.rst
> +- Start simulator_teamplayer *without* game controller (robot will walk in and do it's thing):
it's -> its

2023-09-08 13:47 UTC, timonegk approved these changes

2023-09-08 13:49 UTC, merged